### ISSUE TITLE
你好，关于vuex的问题

### ISSUE THREAD

**Issue by sumincy** [chinanf-boy/AcFun-weex#1]
我在使用vuex 时 web端 使用没有问题 
 集成在android 端时就会显示 TypeError: undefined is not an object (evaluating 'this.$store.state')__ERROR
找不到store 导致页面卡住
vuex 还有哪些地方需要配置吗

**Comment by chinanf-boy** [comment]
额, 这个项目只是试试手
不过, 很乐意帮忙
weex 就是为了让 在web上写的程序, 能平滑 转化到 手机平台源码

你说得这个问题, 如果你是一开始, 搞weex

你应该试试https://github.com/weexteam/weex-hackernews
这个项目是否运行得了, 如果可以, 基本配置也不会有太大不同-

> tips 我的是转IOS, 并没有尝试android

你的问题主要看 `src/store` 目录 下的文件和
项目主文件https://sourcegraph.com/github.com/weexteam/weex-hackernews/-/blob/src/entry.js

希望对你有用

**Comment by sumincy** [comment]
@chinanf-boy  谢谢，我再看看
